export enum MESSAGE_TYPE {
  UPDATE_INTERCEPT_RULES = 'UPDATE_INTERCEPT_RULES',
  GET_INTERCEPT_RULES = 'GET_INTERCEPT_RULES'
}

export const STATIC_STORAGE_KEY = 'local:STATIC_INTERCEPT_RULES'
export const API_STORAGE_KEY = 'local:API_INTERCEPT_RULES'
